### ISSUE TITLE
LambdaUpdateCodeStage may not effectively publish the function after updating the code

### ISSUE THREAD

**Issue by nimakaviani** [spinnaker-plugins/aws-lambda-deployment-plugin-spinnaker#89]
- **High level summary / overview of the issue (think TLDR)**

` LambdaUpdateCodeStage` may not effectively publish the function after updating the code. This could result in traffic getting routed to the older version of the function.

- **Details of the environment.**
    - _What is the version of the plugin?_ 1.0.7
    - _What is the version of spinnaker?_ 1.26

- **Current behavior**
    - _Detailed description of the problematic behavior seen_
       Deploying a function, followed by an update to the function could, and then routing traffic to it can result in lambda responding with an older version of the function.

    - _Which stage is failing?_  `RouteLambdaTrafficStage`
    - _Which task within the stage is failing?_ `LambdaTrafficUpdateTask`
    - _Include a screen shot from detailed task executions for a stage_ 
![image](https://user-images.githubusercontent.com/17132353/127267532-1d96af51-47c5-4e19-9836-bca595f1d2f8.png)

- **Expected behavior (_Detailed description of the expected behavior and how it is different from the current behavior_).**

It is expected that after updating the code for the function, routing traffic to the function should result in the latest version of the function with the expected code changes to respond back to the requests.

- **Steps for how to reproduce (_Please include Spinnaker JSON blobs and parameter values as reference where applicable_)**

```
{
  "appConfig": {},
  "expectedArtifacts": [],
  "keepWaitingPipelines": false,
  "lastModifiedBy": "admin",
  "limitConcurrent": true,
  "parameterConfig": [],
  "spinLibJsonnetVersion": "0.0.0",
  "stages": [
    {
      "account": "my-aws-account",
      "aliases": [
        "v4"
      ],
      "batchsize": 10,
      "cloudProvider": "aws",
      "deadLetterConfig": {
        "targetArn": ""
      },
      "detailName": "",
      "enableLambdaAtEdge": false,
      "envVariables": {
        "TEST_VAR": "my_value"
      },
      "functionName": "lambda-mystack-my-function2",
      "functionUid": "my-function2",
      "handler": "main",
      "memorySize": 128,
      "name": "Deploy Spinnaker Deploy Lambda",
      "publish": true,
      "refId": "6",
      "region": "us-east-1",
      "requisiteStageRefIds": [],
      "reservedConcurrentExecutions": 10,
      "role": "arn:aws:iam::xxx",
      "runtime": "go1.x",
      "s3bucket": "lambda-bucket-east",
      "s3key": "func1.zip",
      "securityGroupIds": [
        "sg-zzz"
      ],
      "stackName": "mystack",
      "subnetIds": [
        "subnet-xxx,
        "subnet-xxxx"
      ],
      "tags": {
        "adsk:moniker": "lambda",
        "purpose": "Lambda Deployment",
        "squad": "Fauda"
      },
      "timeout": 90,
      "tracingConfig": {
        "mode": "PassThrough"
      },
      "triggerArns": [
        "arn:aws:kinesis:us-xxx"
      ],
      "type": "Aws.LambdaDeploymentStage",
      "vpcId": "vpc-xxx"
    },
    {
      "account": "my-aws-account",
      "aliasName": "v4",
      "deploymentStrategy": "$BLUEGREEN",
      "destroyOnFail": true,
      "functionName": "lambda-mystack-my-function2",
      "healthCheckType": "$LAMBDA",
      "name": "AWS Lambda Routing",
      "outputArtifact": {
        "account": "embedded-artifact",
        "artifact": {
          "artifactAccount": "embedded-artifact",
          "id": "fce2deaf-6cdc-4813-95bb-938ddf5f1581",
          "name": "result",
          "reference": "IlN1cCBqYWNrISI=",
          "type": "embedded/base64"
        }
      },
      "payloadArtifact": {
        "account": "embedded-artifact",
        "artifact": {
          "artifactAccount": "embedded-artifact",
          "id": "8ea866d2-f2a2-4d63-8be9-a402cf2a375f",
          "name": "payload",
          "reference": "ewogICJOYW1lIjogImphY2siCn0=",
          "type": "embedded/base64"
        }
      },
      "refId": "7",
      "region": "us-east-1",
      "requisiteStageRefIds": [
        "9"
      ],
      "timeout": 30,
      "type": "Aws.LambdaTrafficRoutingStage"
    },
    {
      "account": "my-aws-account",
      "functionName": "lambda-mystack-my-function2",
      "name": "AWS Lambda Delete",
      "refId": "8",
      "region": "us-east-1",
      "requisiteStageRefIds": [
        "7"
      ],
      "type": "Aws.LambdaDeleteStage",
      "version": "$ALL"
    },
    {
      "account": "my-aws-account",
      "functionName": "lambda-mystack-my-function2",
      "name": "AWS Lambda Update Code",
      "publish": true,
      "refId": "9",
      "region": "us-east-1",
      "requisiteStageRefIds": [
        "6"
      ],
      "s3bucket": "lambda-bucket-east",
      "s3key": "func2.zip",
      "type": "Aws.LambdaUpdateCodeStage"
    }
  ],
  "triggers": [],
  "updateTs": "1627446556000"
}
```

I believe the error is happening because unlike the `LambdaDeploy` stage where we publish the deployed revision of the function and wait for the published revision to appear in the cache, when we update the code, we donot respect whether or not the `publish` flag is checked and do not wait for the new revision to be published prior to routing traffic to it. should be an easy fix, is the problem is due to not properly publishing the latest revision of the function.

**Comment by dkirillov** [comment]
I've tried to reproduce today and found a bit more detail on this issue. Particularly, it only effects newly deploy lambda functions - if a lambda function has been deployed and published a version once, subsequent runs don't seem to be be affected by this bug.

The stages used are - _"AWS Lambda Deployment"_, _"AWS Lambda Update Code"_, _"AWS Lambda Route"_
The _"AWS Lambda Route_ is used primary to send a payload and check that it receives the expected output - if it doesn't receive the expected output, it fails.

The first set of 3 runs looked like the following:
![Screen_Shot_2021-08-16_at_10_54_20_AM](https://user-images.githubusercontent.com/1696313/129606512-da673b87-057a-48aa-8541-d33526b38c63.png)
![Screen_Shot_2021-08-16_at_10_49_40_AM](https://user-images.githubusercontent.com/1696313/129606534-f4559c3c-6b89-4ede-9dce-9f32ab13b346.png)
![Screen_Shot_2021-08-16_at_10_56_23_AM](https://user-images.githubusercontent.com/1696313/129606591-c2de42b0-72d3-4c0c-858b-170f01633d83.png)
The versions also seem to be a bit off. The first time that the pipeline ran, only 1 version was created. The second time that the pipeline ran, 3 versions were created. And third time that it ran, 2 versions. It makes sense that there would be 6 versions ((1 deploy + 1 update) * 3 runs = 6 versions), however the groups/runs in which they got created in don't make sense.

The first time that the pipeline ran, it crashed, subsequent runs - with the same parameters - succeeded. This got me thinking that it needs to be a new lambda.

The error for the route stage was as expected, the event was sent to an old/not-updated version of the lambda, which caused it to crash.

I deleted the lambda, by hand, and did another set of 3 runs.

Second set of 3 runs turned out the same:
![Screen_Shot_2021-08-16_at_11_14_31_AM](https://user-images.githubusercontent.com/1696313/129607389-2a23d24b-b434-4a7b-adb0-109ab23d3f82.png)
![Screen_Shot_2021-08-16_at_11_01_46_AM](https://user-images.githubusercontent.com/1696313/129607401-6eeb1e9b-6ee4-4cb1-9392-533967f826b5.png)
![Screen_Shot_2021-08-16_at_11_08_13_AM](https://user-images.githubusercontent.com/1696313/129607406-02b9b054-518d-4d8d-9bca-59aaad28e3a7.png)
![Screen_Shot_2021-08-16_at_11_14_53_AM](https://user-images.githubusercontent.com/1696313/129607451-8cccad6e-0e6c-4597-95b6-b95f182fc2cf.png)
Again, the first pipeline - that created the new lambda - route stage failed due to the code not being updated, but subsequent runs it passed because the code was updated.

The groups in which the versions were created this time were slightly different. Run 1 produced 1 version (7). Run 2 produced 2 versions (8,9). Run 3 produced 3 versions (10, 11, 12). The number of version, 6, makes sense - but again, how/their-grouping doesn't make sense.

Another interesting thing with versions - the second set started with version 7. This I'm guessing is that the version gets leftover in Spinnaker's cache. But, this is a separate issue from the original one.

----

Captured this in a pipeline that can be re-ran on schedule:
![Screen_Shot_2021-08-16_at_11_37_29_AM](https://user-images.githubusercontent.com/1696313/129610454-a30ad1a9-a307-4ff2-9489-c52cbbc3c2ef.png)

The JSON presentation of the pipeline above (modify values to fit your environment):
https://gist.github.com/dkirillov/609bf63587989bff6464be2fdda04363 (too long to paste in here)
